FROM robertdj/r-base:4.0.4

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
            libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

RUN Rscript -e 'install.packages("xml2")'

